const Data = [
  {
    id: 1,
    name: "length of the lungki",
    description:
      "Everywhere from South Asia to the Horn of Africa and southern Arabian pen",
    price: 120.0,
    rate: 5,
    imgs: [
      "/icons/i2.png",
      "/icons/i3.png",
      "/icons/i4.png",
      "/icons/i5.png",
      "/icons/i6.png",
    ],
    isNew: false,
    category: ["Apparels", "Pants"],
  },
  {
    id: 2,
    name: "the continuous length",
    description:
      "Inspired by the continuous length of the lungki or sarong seen in hot climates Africa and southern Arabian pen",
    price: 599.0,
    rate: 4,
    imgs: [
      "/icons/i1.png",
      "/icons/i2.png",
      "/icons/i3.png",
      "/icons/i4.png",
      "/icons/i5.png",
    ],
    isNew: true,
    category: ["Apparels", "Jumpsuits"],
  },
  {
    id: 3,
    name: "Pueraria Mirifica And Study Phyto Estrogens",
    description:
      "Inspired by the continuous length of the lungki or sarong seen in hot climates everywhere from South Asia to the Horn of Africa and southern Arabian pen",
    price: 799.0,
    rate: 2,
    imgs: [
      "/icons/i3.png",
      "/icons/i2.png",
      "/icons/i4.png",
      "/icons/i5.png",
      "/icons/i6.png",
    ],
    isNew: false,
    category: ["Apparels", "Shorts"],
  },
  {
    id: 4,
    name: "Inspired by the continuous ",
    description:
      "Inspired by the continuous length of the lungki or sarong seen in hot climates everywhere from South Asia to the Horn of Africa and southern Arabian pen",
    price: 690.0,
    rate: 4,
    imgs: [
      "/icons/i4.png",
      "/icons/i2.png",
      "/icons/i3.png",
      "/icons/i5.png",
      "/icons/i6.png",
    ],
    isNew: false,
    category: ["Apparels", "Tops"],
  },
  {
    id: 5,
    name: "Pueraria Mirifica And Study Phyto Estrogens",
    description:
      "Inspired by the continuous length of the lungki or sarong seen in hot climates everywhere from South Asia to the Horn of Africa and southern Arabian pen",
    price: 555.0,
    rate: 0,
    imgs: ["/icons/i5.png", "/icons/i2.png", "/icons/i3.png", "/icons/i6.png"],
    isNew: true,
    category: ["Apparels", "Tops"],
  },
  {
    id: 6,
    name: "Pueraria Mirifica And Study Phyto Estrogens",
    description:
      "Inspired by the continuous length of the lungki or sarong seen in hot climates everywhere from South Asia to the Horn of Africa and southern Arabian pen",
    price: 500.0,
    rate: 1,
    imgs: [
      "/icons/i6.png",
      "/icons/i2.png",
      "/icons/i3.png",
      "/icons/i4.png",
      "/icons/i5.png",
    ],
    isNew: true,
    category: ["Apparels", "Tops"],
  },
  {
    id: 7,
    name: "Pueraria Mirifica And Study Phyto Estrogens",
    description:
      "Inspired by the continuous length of the lungki or sarong seen in hot climates everywhere from South Asia to the Horn of Africa and southern Arabian pen",
    price: 888.0,
    rate: 3,
    imgs: [
      "/icons/i7.png",
      "/icons/i2.png",
      "/icons/i3.png",
      "/icons/i4.png",
      "/icons/i5.png",
    ],
    isNew: true,
    category: ["Accessories", "Tops"],
  },
  {
    id: 8,
    name: "Pueraria Mirifica And Study Phyto Estrogens",
    description:
      "Inspired by the continuous length of the lungki or sarong seen in hot climates everywhere from South Asia to the Horn of Africa and southern Arabian pen",
    price: 599.0,
    rate: 5,
    imgs: [
      "/icons/i1.png",
      "/icons/i2.png",
      "/icons/i3.png",
      "/icons/i4.png",
      "/icons/i5.png",
      "/icons/i6.png",
    ],
    isNew: true,
    category: ["Styles", "Bold"],
  },
  {
    id: 9,
    name: "Pueraria Mirifica And Study Phyto Estrogens",
    description:
      "Inspired by the continuous length of the lungki or sarong seen in hot climates everywhere from South Asia to the Horn of Africa and southern Arabian pen",
    price: 599.0,
    rate: 5,
    imgs: [
      "/icons/i1.png",
      "/icons/i2.png",
      "/icons/i3.png",
      "/icons/i4.png",
      "/icons/i5.png",
      "/icons/i6.png",
    ],
    isNew: true,
    category: ["Styles", "Monochrome"],
  },
  {
    id: 10,
    name: "Pueraria Mirifica And Study Phyto Estrogens",
    description:
      "Inspired by the continuous length of the lungki or sarong seen in hot climates everywhere from South Asia to the Horn of Africa and southern Arabian pen",
    price: 599.0,
    rate: 5,
    imgs: [
      "/icons/i7.png",
      "/icons/i2.png",
      "/icons/i3.png",
      "/icons/i4.png",
      "/icons/i5.png",
      "/icons/i6.png",
    ],
    isNew: true,
    category: ["Styles", "Neutrals"],
  },
  {
    id: 100,
    name: "And Study Phyto Estrogens",
    description:
      "Everywhere from South Asia to the Horn of Africa and southern Arabian pen",
    price: 120.0,
    rate: 5,
    imgs: [
      "/icons/i5.png",
      "/icons/i3.png",
      "/icons/i4.png",
      "/icons/i5.png",
      "/icons/i6.png",
    ],
    isNew: false,
    category: ["Apparels", "Pants"],
  },
  {
    id: 200,
    name: "Phyto Estrogens",
    description:
      "Inspired by the continuous length of the lungki or sarong seen in hot climates Africa and southern Arabian pen",
    price: 599.0,
    rate: 4,
    imgs: [
      "/icons/i2.png",
      "/icons/i2.png",
      "/icons/i3.png",
      "/icons/i4.png",
      "/icons/i5.png",
    ],
    isNew: true,
    category: ["Apparels", "Jumpsuits"],
  },
  {
    id: 300,
    name: "Pueraria Mirifica And Study Phyto Estrogens",
    description:
      "Inspired by the continuous length of the lungki or sarong seen in hot climates everywhere from South Asia to the Horn of Africa and southern Arabian pen",
    price: 799.0,
    rate: 2,
    imgs: [
      "/icons/i6.png",
      "/icons/i2.png",
      "/icons/i4.png",
      "/icons/i5.png",
      "/icons/i6.png",
    ],
    isNew: false,
    category: ["Apparels", "Shorts"],
  },
  {
    id: 400,
    name: "Pueraria Mirifica And Study Phyto Estrogens",
    description:
      "Inspired by the continuous length of the lungki or sarong seen in hot climates everywhere from South Asia to the Horn of Africa and southern Arabian pen",
    price: 690.0,
    rate: 4,
    imgs: [
      "/icons/i1.png",
      "/icons/i2.png",
      "/icons/i3.png",
      "/icons/i5.png",
      "/icons/i6.png",
    ],
    isNew: false,
    category: ["Apparels", "Tops"],
  },
  {
    id: 500,
    name: "Pueraria Mirifica And Study Phyto Estrogens",
    description:
      "Inspired by the continuous length of the lungki or sarong seen in hot climates everywhere from South Asia to the Horn of Africa and southern Arabian pen",
    price: 555.0,
    rate: 0,
    imgs: ["/icons/i5.png", "/icons/i2.png", "/icons/i3.png", "/icons/i6.png"],
    isNew: true,
    category: ["Apparels", "Tops"],
  },
  {
    id: 600,
    name: "Pueraria Mirifica And Study Phyto Estrogens",
    description:
      "Inspired by the continuous length of the lungki or sarong seen in hot climates everywhere from South Asia to the Horn of Africa and southern Arabian pen",
    price: 500.0,
    rate: 1,
    imgs: [
      "/icons/i4.png",
      "/icons/i2.png",
      "/icons/i3.png",
      "/icons/i4.png",
      "/icons/i5.png",
    ],
    isNew: true,
    category: ["Apparels", "Tops"],
  },
  {
    id: 700,
    name: "Pueraria Mirifica And Study Phyto Estrogens",
    description:
      "Inspired by the continuous length of the lungki or sarong seen in hot climates everywhere from South Asia to the Horn of Africa and southern Arabian pen",
    price: 888.0,
    rate: 3,
    imgs: [
      "/icons/i7.png",
      "/icons/i2.png",
      "/icons/i3.png",
      "/icons/i4.png",
      "/icons/i5.png",
    ],
    isNew: true,
    category: ["Accessories", "Tops"],
  },
  {
    id: 800,
    name: "Pueraria Mirifica And Study Phyto Estrogens",
    description:
      "Inspired by the continuous length of the lungki or sarong seen in hot climates everywhere from South Asia to the Horn of Africa and southern Arabian pen",
    price: 599.0,
    rate: 5,
    imgs: [
      "/icons/i4.png",
      "/icons/i2.png",
      "/icons/i3.png",
      "/icons/i4.png",
      "/icons/i5.png",
      "/icons/i6.png",
    ],
    isNew: true,
    category: ["Styles", "Bold"],
  },
  {
    id: 900,
    name: "Pueraria Mirifica And Study Phyto Estrogens",
    description:
      "Inspired by the continuous length of the lungki or sarong seen in hot climates everywhere from South Asia to the Horn of Africa and southern Arabian pen",
    price: 599.0,
    rate: 5,
    imgs: [
      "/icons/i6.png",
      "/icons/i2.png",
      "/icons/i3.png",
      "/icons/i4.png",
      "/icons/i5.png",
      "/icons/i6.png",
    ],
    isNew: true,
    category: ["Styles", "Monochrome"],
  },
  {
    id: 1000,
    name: "Pueraria Mirifica And Study Phyto Estrogens",
    description:
      "Inspired by the continuous length of the lungki or sarong seen in hot climates everywhere from South Asia to the Horn of Africa and southern Arabian pen",
    price: 599.0,
    rate: 5,
    imgs: [
      "/icons/i5.png",
      "/icons/i2.png",
      "/icons/i3.png",
      "/icons/i4.png",
      "/icons/i5.png",
      "/icons/i6.png",
    ],
    isNew: true,
    category: ["Styles", "Neutrals"],
  },
];

export default Data;
